/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './toast.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from './toast-manager';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from './toast-container.component.ngfactory';
import * as import7 from '@angular/core/src/application_ref';
import * as import8 from './toast-options';
import * as import9 from '@angular/core/src/i18n/tokens';
class ToastModuleInjector extends import0.NgModuleInjector<import1.ToastModule> {
  _CommonModule_0:import2.CommonModule;
  _ToastModule_1:import1.ToastModule;
  __LOCALE_ID_2:any;
  __NgLocalization_3:import3.NgLocaleLocalization;
  __ToastsManager_4:import4.ToastsManager;
  __TRANSLATIONS_FORMAT_5:any;
  constructor(parent:import5.Injector) {
    super(parent,[import6.ToastContainerNgFactory],[]);
  }
  get _LOCALE_ID_2():any {
    if ((this.__LOCALE_ID_2 == (null as any))) { (this.__LOCALE_ID_2 = (null as any)); }
    return this.__LOCALE_ID_2;
  }
  get _NgLocalization_3():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == (null as any))) { (this.__NgLocalization_3 = new import3.NgLocaleLocalization(this._LOCALE_ID_2)); }
    return this.__NgLocalization_3;
  }
  get _ToastsManager_4():import4.ToastsManager {
    if ((this.__ToastsManager_4 == (null as any))) { (this.__ToastsManager_4 = new import4.ToastsManager(this,this.parent.get(import7.ApplicationRef),this.parent.get(import8.ToastOptions,(null as any)))); }
    return this.__ToastsManager_4;
  }
  get _TRANSLATIONS_FORMAT_5():any {
    if ((this.__TRANSLATIONS_FORMAT_5 == (null as any))) { (this.__TRANSLATIONS_FORMAT_5 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_5;
  }
  createInternal():import1.ToastModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ToastModule_1 = new import1.ToastModule();
    return this._ToastModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.ToastModule)) { return this._ToastModule_1; }
    if ((token === import9.LOCALE_ID)) { return this._LOCALE_ID_2; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import4.ToastsManager)) { return this._ToastsManager_4; }
    if ((token === import9.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ToastModuleNgFactory:import0.NgModuleFactory<import1.ToastModule> = new import0.NgModuleFactory(ToastModuleInjector,import1.ToastModule);